language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x ./heroku_deploy.sh
  - nvm install 7
  - npm install -g npm@3.10.10
  - cd src/main/webapp/WEB-INF/res/app/js
  - npm install
  - npm run webpack
  - npm run transpile
  - cd ../../../../../../..

# build safelist
branches:
  only:
  - master
  - dev

# codecov integration
#script: "mvn cobertura:cobertura"
#after_success:
#  - bash <(curl -s https://codecov.io/bash)


# deployment
before_deploy:
  - git config user.email "hobbydev.public@gmail.com"
  - git config user.name "HobbyDev Public"
  - ./heroku_deploy.sh
  - cd src/main/webapp/WEB-INF/res/app/js
  - git add -f dist/*.js
  - git add -f node_modules/bootstrap/dist
  - git add -f node_modules/font-awesome/css
  - git add -f node_modules/font-awesome/fonts
  - git add -f node_modules/admin-lte/dist
  - git add -f node_modules/admin-lte/plugins/slimScroll
  - git add -f node_modules/angular-ui-grid/ui-grid.css
  - git commit -q --no-status -a -m "adding heroku environment definition and building FE"
  - cd ../../../../../../..

deploy:
  provider: heroku
  api_key: cc5e6c3f-805f-42d1-955e-6bbbf39fa0b1
  app:
    master: s-planner
    dev: s-planner-dev

# notifications
notifications:
  slack: hobbydev:teIsXPUWmiJ5g4Qxpyo2WdQd